# Generated by Django 4.0.4 on 2024-05-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airplane',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='crew',
            name='flights',
        ),
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(to='airport.crew'),
        ),
    ]
