# Generated by Django 4.0.4 on 2024-05-13 22:18

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_alter_ticket_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='airplanetype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['id', 'departure_time', 'arrival_time']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='airplane',
            name='airplane_image',
            field=models.ImageField(blank=True, null=True, upload_to=airport.models.airplane_image_file_path),
        ),
    ]
